SELECT TBL_VOOS.NR_VOO, 
   TBL_VOOS.DT_VOO AS DATA_VOO,
   TBL_AERONAVES.CD_CALDA,
   TBL_AERONAVES.NM_AERONAVE AS NOME_AERONAVE
FROM TBL_VOOS
INNER JOIN TBL_AERONAVES ON TBL_VOOS.CD_CALDA = TBL_AERONAVES.CD_CALDA