ALTER TABLE TBL_VOOS DROP CONSTRAINT VOO_FK FOREIGN KEY;

DROP TABLE TBL_VOOS;
DROP TABLE TBL_AERONAVES;

DROP SEQUENCE SEQ_TBL_AERONAVES;
DROP SEQUENCE SEQ_TBL_VOOS;

CREATE SEQUENCE SEQ_TBL_VOOS;

CREATE TABLE TBL_AERONAVES (    
CD_CALDA VARCHAR2(250) NOT NULL,
NM_AERONAVE VARCHAR2(250) NOT NULL,
CONSTRAINT AERONAVE_PK PRIMARY KEY (CD_CALDA)
);

CREATE TABLE TBL_VOOS (
NR_VOO NUMBER NOT NULL,
DT_VOO DATE NOT NULL,
CD_CALDA VARCHAR2(250) NOT NULL,
CONSTRAINT VOO_PK PRIMARY KEY (NR_VOO)
);

ALTER TABLE TBL_VOOS ADD CONSTRAINT VOO_FK FOREIGN KEY (CD_CALDA)
REFERENCES TBL_AERONAVES (CD_CALDA)
NOT DEFERRABLE;


