INSERT INTO TBL_AERONAVES VALUES ('R-896', 'GULFSTREAM G450');
INSERT INTO TBL_AERONAVES VALUES ('A-96A', 'GULFSTREAM G650');
INSERT INTO TBL_AERONAVES VALUES ('52E', 'BOEING 747');
INSERT INTO TBL_AERONAVES VALUES ('B-07', 'BOEING 747');


INSERT INTO TBL_VOOS VALUES (SEQ_TBL_VOOS.NEXTVAL, TO_DATE('31/12/2023', 'DD/MM/YYYY'), 'R-896');
INSERT INTO TBL_VOOS VALUES (SEQ_TBL_VOOS.NEXTVAL, TO_DATE('01/01/2024', 'DD/MM/YYYY'), 'A-96A');
INSERT INTO TBL_VOOS VALUES (SEQ_TBL_VOOS.NEXTVAL, TO_DATE('21/10/2023', 'DD/MM/YYYY'), 'B-07');
INSERT INTO TBL_VOOS VALUES (SEQ_TBL_VOOS.NEXTVAL, TO_DATE('07/11/2023', 'DD/MM/YYYY'), '52E');